[package]
name = "xbrew"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.22.0", features = ["full"] }
reqwest = "0.11.13"
exitfailure = "0.5.1"
serde_derive = "1.0.147"