name: Bobert the buildbot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: ./scripts/dev-setup.sh
      
    - name: Build code
      run: make 
